settings:
  title: 'Shadiao Status'
  url: 'https://status.space586.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: space586-com # unique identifier
    name: space586.com
    description: 'Look your mother look' # default=empty
    url: 'https://space586.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: pan-space586-com
    name: pan.space586.com
    description: '这是好的'
    url: 'https://pan.space586.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: pic-space586-com
    name: pic.space586.com
    url: 'https://pic.space586.com/'
    method: GET
    expectStatus: 200

  - id: lpan-cc
    name: lpan.cc
    url: 'https://lpan.cc'
    method: GET
    expectStatus: 200
